/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Home;
import java.awt.HeadlessException;
import java.sql.*;
import java.text.MessageFormat;
import java.awt.print.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Salman_Lap
 */
public class BloodBrowser extends javax.swing.JFrame {
    
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    DefaultTableModel dm;


    /** Creates new form BloodBrowser */
    public BloodBrowser() {
        super("Blood Group Adminstration");

        
        
        conn=DataConnect.DataConn();
       
        
        initComponents();
     
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        fetch();
       
    }
    
   
    
   
    
   
    public void find(String id){



        String sql="select * from Donors where DonorID='"+id+"'";



        DataFound ob=new DataFound();
        ob.setVisible(true);
        ob.showData(id);

    }
    
    public void fetch(){
        try{
            
            String sql="SELECT * FROM Donors";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            showAll.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null,e);
            
            
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showAll = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton6.setIcon(new javax.swing.ImageIcon("E:\\STUDIES\\AAAAAAJAVAAAAAAAAAAAAAAAAA\\Projects\\Blood Group Administration\\miscellaneous files\\Delete.png")); // NOI18N
        jButton6.setText("Delete Data");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\STUDIES\\AAAAAAJAVAAAAAAAAAAAAAAAAA\\Projects\\Blood Group Administration\\miscellaneous files\\refresh.png")); // NOI18N
        jButton1.setText("Refresh List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("E:\\STUDIES\\AAAAAAJAVAAAAAAAAAAAAAAAAA\\Projects\\Blood Group Administration\\miscellaneous files\\Add.png")); // NOI18N
        jButton3.setText("ADD NEW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("E:\\STUDIES\\AAAAAAJAVAAAAAAAAAAAAAAAAA\\Projects\\Blood Group Administration\\miscellaneous files\\Search.png")); // NOI18N
        jButton4.setText("Find Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Donor ID:");

        jButton5.setIcon(new javax.swing.ImageIcon("E:\\STUDIES\\AAAAAAJAVAAAAAAAAAAAAAAAAA\\Projects\\Blood Group Administration\\miscellaneous files\\update.png")); // NOI18N
        jButton5.setText("Update Data");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        showAll.setAutoCreateRowSorter(true);
        showAll.setBackground(new java.awt.Color(204, 0, 51));
        showAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(showAll);

        jButton7.setIcon(new javax.swing.ImageIcon("E:\\STUDIES\\AAAAAAJAVAAAAAAAAAAAAAAAAA\\Projects\\Blood Group Administration\\miscellaneous files\\Exit.png")); // NOI18N
        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\STUDIES\\AAAAAAJAVAAAAAAAAAAAAAAAAA\\Projects\\Blood Group Administration\\miscellaneous files\\firstLogo2.png")); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon("E:\\STUDIES\\AAAAAAJAVAAAAAAAAAAAAAAAAA\\Projects\\Blood Group Administration\\miscellaneous files\\Login.png")); // NOI18N
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon("E:\\STUDIES\\AAAAAAJAVAAAAAAAAAAAAAAAAA\\Projects\\Blood Group Administration\\miscellaneous files\\print.png")); // NOI18N
        jButton8.setText("Print Table");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton5)
                        .addGap(62, 62, 62)
                        .addComponent(jButton6)
                        .addGap(50, 50, 50)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton2)
                    .addComponent(jButton8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fetch();
        //jTextArea1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Add ob=new Add();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id=jTextField1.getText();
        System.out.println(id);
        String sql="select * from Donors where DonorID='"+id+"'";
        if(!id.equals("")){
            try{
                pst=conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    pst.close();
                    rs.close();
                    find(id);
                }else{
                    JOptionPane.showMessageDialog(null, "Incorrect ID");
                }

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally{
                try{
                    pst.close();
                    rs.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            }
        }

        else{
            JOptionPane.showMessageDialog(null, "Please insert DonorID");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //Update ob=new Update();
        //ob.setVisible(true);
       try{ DefaultTableModel model=(DefaultTableModel)showAll.getModel();
        int select=showAll.getSelectedRow();
        String id=model.getValueAt(select, 0).toString();
        
        String name=model.getValueAt(select, 1).toString();
        String email=model.getValueAt(select, 2).toString();
        String Phone=model.getValueAt(select, 3).toString();
        String adress=model.getValueAt(select, 4).toString();
        String Last_donated=model.getValueAt(select, 5).toString();
        String Blood=model.getValueAt(select, 6).toString();
        
        Update ob=new Update();
        ob.getID(id);
        ob.setInfo(name, email, Phone, adress, Last_donated, Blood);
        ob.setVisible(true);
        JOptionPane.showMessageDialog(null, "Please leave unchanged where you don't want to update!");
        
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Please select a donor to update!");
       }
        //String newAdress=JOptionPane.showInputDialog(null,"Enter new adress",adress);
        //System.out.println("Current id:"+id+"name:"+name+"email:"+email+"Phone:"+Phone);
    }//GEN-LAST:event_jButton5ActionPerformed

    
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Are you sure to Exit?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
  
         System.exit(0);
}
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        try{ DefaultTableModel model=(DefaultTableModel)showAll.getModel();
        int select=showAll.getSelectedRow();
        String id=model.getValueAt(select, 0).toString();
        String sql="DELETE FROM Donors WHERE DonorID='"+id+"'";
        pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Successfully Deleted donor "+id+"!");
            fetch();
               }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please select a donor to delete!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        MessageFormat header=new MessageFormat("Blood Donors Print");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        
        try{
            showAll.print(JTable.PrintMode.NORMAL,header,footer);
        }catch(java.awt.print.PrinterException e){
            System.err.format("can not print %s%n", e.getMessage());
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BloodBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BloodBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BloodBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BloodBrowser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BloodBrowser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTable showAll;
    // End of variables declaration//GEN-END:variables

}
